### ISSUE TITLE
Can't get info of online server

### ISSUE THREAD

**Issue by HuyMaster** [PsychOps/serverpinger#6] opened 2022-02-09 23:26 UTC
I started my server and executed the command. Instead it shows the status of the server, it shows this error
![image](https://user-images.githubusercontent.com/80255843/153307564-bd682b26-cf16-42c1-bde9-6e9c9eafa548.png)

My server setting
![image](https://user-images.githubusercontent.com/80255843/153307949-4c5cfd08-dd74-44be-8e63-7d5be6eb802d.png)

**Comment by BluewyWolff** [comment] 2022-02-09 23:40
Hi! Thank you for opening an issue.
Could you please inform me what your server software and version is?

**Comment by HuyMaster** [comment] 2022-02-10 05:09
> Hi! Thank you for opening an issue. Could you please inform me what your server software and version is?

Software : Forge
Version 1.7.10 (Forge 10.13.4.1614)

**Comment by ToothyDev** [comment] 2022-02-17 18:17
Hi! The issue you have seems to be linked to your MOTD, so we recommend you to temporarily remove that until the issue is resolved. We will comment back on this issue once that's the case.

**Comment by HuyMaster** [comment] 2022-02-18 05:10
I deleted MOTD but the problem still happened
![image](https://user-images.githubusercontent.com/80255843/154621484-879147b5-52d5-4c56-9966-3f4a539e2e31.png)

**Comment by BluewyWolff** [comment] 2022-02-18 10:56
This issue has been fixed in https://github.com/PsychOps/serverpinger/commit/91bf02610b15e9cd1a96a536188005a992fb0fcc.

The issue here was that any forge server would break because the protocol used to check server status' gave a different format for MOTDs with forge servers while having a different format for plugin servers. Thank you for giving us awareness of this issue and please do let us know if any others occur.

**Closed by BluewyWolff** 2022-02-18 10:56 UTC
Labels: bug
